version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2

    steps:
      - checkout  # Checkout source code from the repository

      - run:
          name: Install Dependencies  # Install Maven dependencies
          command: mvn dependency:go-offline

      - run:
          name: Build and Test  # Build and run tests
          command: mvn test

      - run:
          name: Generate JaCoCo Coverage Report  # Generate JaCoCo coverage report
          command: mvn jacoco:report

      - codecov/upload:  # Upload coverage reports to Codecov
          token: ${{ secrets.CODECOV_TOKEN }}

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
