version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline

      - run:
          name: Build and Test
          command: mvn test

      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn jacoco:report

  upload-to-codecov:
    docker:
      - image: cimg/openjdk:21.0.2

    steps:
      - checkout

      - codecov/upload:
          token: $CODECOV_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - upload-to-codecov:
          requires:
            - build
