version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-upload:
    docker:
      - image: cimg/openjdk:21.0.2

    steps:
      - checkout

      # Install Maven dependencies
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve -B

      # Build and run tests
      - run:
          name: Build and Test
          command: |
            mvn clean verify
            mvn jacoco:report

      # Upload coverage report to Codecov
      - codecov/upload:
          token: $CODECOV_TOKEN

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-and-upload:
          filters:
            branches:
              only: master
