version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk  # Use Docker image with Java 11

    steps:
      - checkout  # Checkout source code from the repository

      - run:
          name: Install Dependencies  # Install Maven dependencies
          command: mvn dependency:go-offline

      - run:
          name: Build and Test  # Build and run tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
